# Data Preparation

In [1]:
import os
import pandas as pd
import numpy as np

Set Data Folder Paths

In [2]:
open_meteo_folder = "../Data/Raw/Open_Meteo"
pvgis_folder = "../Data/Raw/PVGIS"

processed_folder = "../Data/Processed"

os.makedirs(
    processed_folder,
    exist_ok=True
)

Identify Open-Meteo and PVGIS Files

In [3]:
open_meteo_files = sorted([
    os.path.join(open_meteo_folder, file)
    for file in os.listdir(open_meteo_folder)
    if file.endswith(".csv")
])

pvgis_files = sorted([
    os.path.join(pvgis_folder, file)
    for file in os.listdir(pvgis_folder)
    if file.endswith(".csv")
])

print("Open-Meteo files:", len(open_meteo_files))
print("PVGIS files:", len(pvgis_files))

Open-Meteo files: 25
PVGIS files: 25

 Load and Combine Open-Meteo Data

In [4]:
open_meteo_list = []

for file in open_meteo_files:
    df = pd.read_csv(file)
    open_meteo_list.append(df)

open_meteo_data = pd.concat(
    open_meteo_list,
    ignore_index=True
)

print("Open-Meteo dataset shape:")
print(open_meteo_data.shape)

Open-Meteo dataset shape:
(438000, 17)

Load and Combine PVGIS Data

In [5]:
pvgis_list = []

for file in pvgis_files:
    df = pd.read_csv(file)
    pvgis_list.append(df)

pvgis_data = pd.concat(
    pvgis_list,
    ignore_index=True
)

print("PVGIS dataset shape:")
print(pvgis_data.shape)

PVGIS dataset shape:
(438000, 10)

Inspect the Combined Datasets

In [6]:
print("Open-Meteo columns:")
print(open_meteo_data.columns.tolist())

print("\nPVGIS columns:")
print(pvgis_data.columns.tolist())

Open-Meteo columns:
['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'cloud_cover', 'wind_speed_10m', 'shortwave_radiation', 'direct_radiation', 'diffuse_radiation', 'direct_normal_irradiance', 'global_tilted_irradiance', 'sunshine_duration', 'is_day', 'district', 'latitude', 'longitude', 'elevation']

PVGIS columns:
['time', 'P', 'G(i)', 'H_sun', 'T2m', 'WS10m', 'Int', 'district', 'latitude', 'longitude']

In [7]:
open_meteo_data.head()

,time,temperature_2m,relative_humidity_2m,precipitation,cloud_cover,wind_speed_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,global_tilted_irradiance,sunshine_duration,is_day,district,latitude,longitude,elevation
0,2022-01-01T00:00,23.0,94,0.2,100,5.4,0.0,0.0,0.0,0.0,0.0,0.00,0,Ampara,7.29754,81.68202,37.0
1,2022-01-01T01:00,23.3,94,0.2,100,4.1,1.0,1.0,0.0,0.0,0.0,0.00,1,Ampara,7.29754,81.68202,37.0
2,2022-01-01T02:00,23.9,92,0.5,100,3.8,43.0,18.0,25.0,110.8,50.6,1572.38,1,Ampara,7.29754,81.68202,37.0
3,2022-01-01T03:00,25.1,87,0.3,100,4.3,161.0,73.0,88.0,191.0,174.2,3600.00,1,Ampara,7.29754,81.68202,37.0
4,2022-01-01T04:00,26.1,84,0.7,100,7.8,348.0,166.0,182.0,288.8,368.2,3600.00,1,Ampara,7.29754,81.68202,37.0

In [8]:
pvgis_data.head()

,time,P,G(i),H_sun,T2m,WS10m,Int,district,latitude,longitude
0,20220101:0030,0.00,0.00,-4.37,23.64,2.21,0.0,Ampara,7.29754,81.68202
1,20220101:0130,29.45,57.05,9.26,23.89,1.66,0.0,Ampara,7.29754,81.68202
2,20220101:0230,138.10,190.06,22.56,24.38,1.24,0.0,Ampara,7.29754,81.68202
3,20220101:0330,284.79,367.82,35.23,25.22,1.52,0.0,Ampara,7.29754,81.68202
4,20220101:0430,487.96,633.72,46.67,26.01,1.66,0.0,Ampara,7.29754,81.68202

Check District Coverage

In [9]:
open_meteo_district_counts = (
    open_meteo_data["district"]
    .value_counts()
    .sort_index()
)

open_meteo_district_counts

district
Ampara          17520
Anuradhapura    17520
Badulla         17520
Batticaloa      17520
Colombo         17520
Galle           17520
Gampaha         17520
Hambantota      17520
Jaffna          17520
Kalutara        17520
Kandy           17520
Kegalle         17520
Kilinochchi     17520
Kurunegala      17520
Mannar          17520
Matale          17520
Matara          17520
Monaragala      17520
Mullaitivu      17520
Nuwara Eliya    17520
Polonnaruwa     17520
Puttalam        17520
Ratnapura       17520
Trincomalee     17520
Vavuniya        17520
Name: count, dtype: int64

In [10]:
pvgis_district_counts = (
    pvgis_data["district"]
    .value_counts()
    .sort_index()
)

pvgis_district_counts

district
Ampara          17520
Anuradhapura    17520
Badulla         17520
Batticaloa      17520
Colombo         17520
Galle           17520
Gampaha         17520
Hambantota      17520
Jaffna          17520
Kalutara        17520
Kandy           17520
Kegalle         17520
Kilinochchi     17520
Kurunegala      17520
Mannar          17520
Matale          17520
Matara          17520
Monaragala      17520
Mullaitivu      17520
Nuwara Eliya    17520
Polonnaruwa     17520
Puttalam        17520
Ratnapura       17520
Trincomalee     17520
Vavuniya        17520
Name: count, dtype: int64

Initial Data Quality Check

In [11]:
print("Open-Meteo missing values:")
print(open_meteo_data.isnull().sum())

print("\nPVGIS missing values:")
print(pvgis_data.isnull().sum())

Open-Meteo missing values:
time                           0
temperature_2m                 0
relative_humidity_2m           0
precipitation               8625
cloud_cover                    0
wind_speed_10m                 0
shortwave_radiation            0
direct_radiation               0
diffuse_radiation              0
direct_normal_irradiance       0
global_tilted_irradiance       0
sunshine_duration              0
is_day                         0
district                       0
latitude                       0
longitude                      0
elevation                      0
dtype: int64

PVGIS missing values:
time         0
P            0
G(i)         0
H_sun        0
T2m          0
WS10m        0
Int          0
district     0
latitude     0
longitude    0
dtype: int64

In [12]:
print(
    "Open-Meteo duplicated rows:",
    open_meteo_data.duplicated().sum()
)

print(
    "PVGIS duplicated rows:",
    pvgis_data.duplicated().sum()
)

Open-Meteo duplicated rows: 0
PVGIS duplicated rows: 0

Check Data Types

In [13]:
print("Open-Meteo data types:")
print(open_meteo_data.dtypes)

print("\nPVGIS data types:")
print(pvgis_data.dtypes)

Open-Meteo data types:
time                         object
temperature_2m              float64
relative_humidity_2m          int64
precipitation               float64
cloud_cover                   int64
wind_speed_10m              float64
shortwave_radiation         float64
direct_radiation            float64
diffuse_radiation           float64
direct_normal_irradiance    float64
global_tilted_irradiance    float64
sunshine_duration           float64
is_day                        int64
district                     object
latitude                    float64
longitude                   float64
elevation                   float64
dtype: object

PVGIS data types:
time          object
P            float64
G(i)         float64
H_sun        float64
T2m          float64
WS10m        float64
Int          float64
district      object
latitude     float64
longitude    float64
dtype: object

Prepare Timestamps

In [14]:
open_meteo_data["time_utc"] = pd.to_datetime(
    open_meteo_data["time"],
    utc=True
)

pvgis_data["pvgis_time_utc"] = pd.to_datetime(
    pvgis_data["time"],
    format="%Y%m%d:%H%M",
    utc=True
)

In [15]:
print("Open-Meteo:")
print(
    open_meteo_data[
        ["time", "time_utc"]
    ].head()
)

print("\nPVGIS:")
print(
    pvgis_data[
        ["time", "pvgis_time_utc"]
    ].head()
)

Open-Meteo:
               time                  time_utc
0  2022-01-01T00:00 2022-01-01 00:00:00+00:00
1  2022-01-01T01:00 2022-01-01 01:00:00+00:00
2  2022-01-01T02:00 2022-01-01 02:00:00+00:00
3  2022-01-01T03:00 2022-01-01 03:00:00+00:00
4  2022-01-01T04:00 2022-01-01 04:00:00+00:00

PVGIS:
            time            pvgis_time_utc
0  20220101:0030 2022-01-01 00:30:00+00:00
1  20220101:0130 2022-01-01 01:30:00+00:00
2  20220101:0230 2022-01-01 02:30:00+00:00
3  20220101:0330 2022-01-01 03:30:00+00:00
4  20220101:0430 2022-01-01 04:30:00+00:00

Align PVGIS Timestamps

In [16]:
pvgis_data["time_utc"] = (
    pvgis_data["pvgis_time_utc"]
    + pd.Timedelta(minutes=30)
)

In [17]:
pvgis_data[
    ["time", "pvgis_time_utc", "time_utc"]
].head()

            time            pvgis_time_utc                  time_utc
0  20220101:0030 2022-01-01 00:30:00+00:00 2022-01-01 01:00:00+00:00
1  20220101:0130 2022-01-01 01:30:00+00:00 2022-01-01 02:00:00+00:00
2  20220101:0230 2022-01-01 02:30:00+00:00 2022-01-01 03:00:00+00:00
3  20220101:0330 2022-01-01 03:30:00+00:00 2022-01-01 04:00:00+00:00
4  20220101:0430 2022-01-01 04:30:00+00:00 2022-01-01 05:00:00+00:00

Check Timestamp Ranges

In [18]:
print("Open-Meteo:")
print(
    open_meteo_data["time_utc"].min(),
    "to",
    open_meteo_data["time_utc"].max()
)

print("\nPVGIS original:")
print(
    pvgis_data["pvgis_time_utc"].min(),
    "to",
    pvgis_data["pvgis_time_utc"].max()
)

print("\nPVGIS aligned:")
print(
    pvgis_data["time_utc"].min(),
    "to",
    pvgis_data["time_utc"].max()
)

Open-Meteo:
2022-01-01 00:00:00+00:00 to 2023-12-31 23:00:00+00:00

PVGIS original:
2022-01-01 00:30:00+00:00 to 2023-12-31 23:30:00+00:00

PVGIS aligned:
2022-01-01 01:00:00+00:00 to 2024-01-01 00:00:00+00:00

Check Timestamp Duplicates

In [19]:
print(
    "Open-Meteo duplicate district/time:",
    open_meteo_data.duplicated(
        subset=["district", "time_utc"]
    ).sum()
)

print(
    "PVGIS duplicate district/time:",
    pvgis_data.duplicated(
        subset=["district", "time_utc"]
    ).sum()
)

Open-Meteo duplicate district/time: 0
PVGIS duplicate district/time: 0

Check Timestamp Matching

In [21]:
timestamp_check = pd.merge(
    open_meteo_data[
        ["district", "time_utc"]
    ],
    pvgis_data[
        ["district", "time_utc"]
    ],
    on=["district", "time_utc"],
    how="outer",
    indicator=True
)

timestamp_check["_merge"].value_counts()

_merge
both          437975
left_only         25
right_only        25
Name: count, dtype: int64

In [22]:
timestamp_check[
    timestamp_check["_merge"] != "both"
].sort_values(
    ["district", "time_utc"]
).head(10)

           district                  time_utc      _merge
0            Ampara 2022-01-01 00:00:00+00:00   left_only
17520        Ampara 2024-01-01 00:00:00+00:00  right_only
17521  Anuradhapura 2022-01-01 00:00:00+00:00   left_only
35041  Anuradhapura 2024-01-01 00:00:00+00:00  right_only
35042       Badulla 2022-01-01 00:00:00+00:00   left_only
52562       Badulla 2024-01-01 00:00:00+00:00  right_only
52563    Batticaloa 2022-01-01 00:00:00+00:00   left_only
70083    Batticaloa 2024-01-01 00:00:00+00:00  right_only
70084       Colombo 2022-01-01 00:00:00+00:00   left_only
87604       Colombo 2024-01-01 00:00:00+00:00  right_only

Prepare PVGIS Columns

In [23]:
pvgis_for_merge = pvgis_data[
    [
        "district",
        "time_utc",
        "pvgis_time_utc",
        "P",
        "G(i)",
        "H_sun",
        "T2m",
        "WS10m",
        "Int"
    ]
].copy()

In [24]:
pvgis_for_merge = pvgis_for_merge.rename(
    columns={
        "G(i)": "pvgis_gi",
        "H_sun": "pvgis_h_sun",
        "T2m": "pvgis_t2m",
        "WS10m": "pvgis_ws10m",
        "Int": "pvgis_int"
    }
)

## Merge Open-Meteo and PVGIS Data

In [25]:
prepared_data = pd.merge(
    open_meteo_data,
    pvgis_for_merge,
    on=["district", "time_utc"],
    how="inner"
)

print("Merged dataset shape:")
print(prepared_data.shape)

Merged dataset shape:
(437975, 25)

In [27]:
prepared_data.head()

,time,temperature_2m,relative_humidity_2m,precipitation,cloud_cover,wind_speed_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,...,longitude,elevation,time_utc,pvgis_time_utc,P,pvgis_gi,pvgis_h_sun,pvgis_t2m,pvgis_ws10m,pvgis_int
0,2022-01-01T01:00,23.3,94,0.2,100,4.1,1.0,1.0,0.0,0.0,...,81.68202,37.0,2022-01-01 01:00:00+00:00,2022-01-01 00:30:00+00:00,0.00,0.00,-4.37,23.64,2.21,0.0
1,2022-01-01T02:00,23.9,92,0.5,100,3.8,43.0,18.0,25.0,110.8,...,81.68202,37.0,2022-01-01 02:00:00+00:00,2022-01-01 01:30:00+00:00,29.45,57.05,9.26,23.89,1.66,0.0
2,2022-01-01T03:00,25.1,87,0.3,100,4.3,161.0,73.0,88.0,191.0,...,81.68202,37.0,2022-01-01 03:00:00+00:00,2022-01-01 02:30:00+00:00,138.10,190.06,22.56,24.38,1.24,0.0
3,2022-01-01T04:00,26.1,84,0.7,100,7.8,348.0,166.0,182.0,288.8,...,81.68202,37.0,2022-01-01 04:00:00+00:00,2022-01-01 03:30:00+00:00,284.79,367.82,35.23,25.22,1.52,0.0
4,2022-01-01T05:00,27.0,80,1.0,79,10.2,619.0,352.0,267.0,485.6,...,81.68202,37.0,2022-01-01 05:00:00+00:00,2022-01-01 04:30:00+00:00,487.96,633.72,46.67,26.01,1.66,0.0

In [28]:
print(
    "Duplicate district/time:",
    prepared_data.duplicated(
        subset=["district", "time_utc"]
    ).sum()
)

print(
    "Districts:",
    prepared_data["district"].nunique()
)

Duplicate district/time: 0
Districts: 25

Add Sri Lanka Local Time

In [29]:
prepared_data["time_sl"] = (
    prepared_data["time_utc"]
    .dt.tz_convert("Asia/Colombo")
)

In [30]:
prepared_data[
    [
        "time_utc",
        "time_sl",
        "district",
        "P"
    ]
].head(10)

                   time_utc                   time_sl district       P
0 2022-01-01 01:00:00+00:00 2022-01-01 06:30:00+05:30   Ampara    0.00
1 2022-01-01 02:00:00+00:00 2022-01-01 07:30:00+05:30   Ampara   29.45
2 2022-01-01 03:00:00+00:00 2022-01-01 08:30:00+05:30   Ampara  138.10
3 2022-01-01 04:00:00+00:00 2022-01-01 09:30:00+05:30   Ampara  284.79
4 2022-01-01 05:00:00+00:00 2022-01-01 10:30:00+05:30   Ampara  487.96
5 2022-01-01 06:00:00+00:00 2022-01-01 11:30:00+05:30   Ampara  378.92
6 2022-01-01 07:00:00+00:00 2022-01-01 12:30:00+05:30   Ampara  546.48
7 2022-01-01 08:00:00+00:00 2022-01-01 13:30:00+05:30   Ampara  524.20
8 2022-01-01 09:00:00+00:00 2022-01-01 14:30:00+05:30   Ampara  254.02
9 2022-01-01 10:00:00+00:00 2022-01-01 15:30:00+05:30   Ampara  212.33

Check Merged District Coverage

In [31]:
prepared_data[
    "district"
].value_counts().sort_index()

district
Ampara          17519
Anuradhapura    17519
Badulla         17519
Batticaloa      17519
Colombo         17519
Galle           17519
Gampaha         17519
Hambantota      17519
Jaffna          17519
Kalutara        17519
Kandy           17519
Kegalle         17519
Kilinochchi     17519
Kurunegala      17519
Mannar          17519
Matale          17519
Matara          17519
Monaragala      17519
Mullaitivu      17519
Nuwara Eliya    17519
Polonnaruwa     17519
Puttalam        17519
Ratnapura       17519
Trincomalee     17519
Vavuniya        17519
Name: count, dtype: int64

Check Missing Values After Merge

In [32]:
prepared_data.isnull().sum()

time                           0
temperature_2m                 0
relative_humidity_2m           0
precipitation               8625
cloud_cover                    0
wind_speed_10m                 0
shortwave_radiation            0
direct_radiation               0
diffuse_radiation              0
direct_normal_irradiance       0
global_tilted_irradiance       0
sunshine_duration              0
is_day                         0
district                       0
latitude                       0
longitude                      0
elevation                      0
time_utc                       0
pvgis_time_utc                 0
P                              0
pvgis_gi                       0
pvgis_h_sun                    0
pvgis_t2m                      0
pvgis_ws10m                    0
pvgis_int                      0
time_sl                        0
dtype: int64

Check Numerical Ranges

In [34]:
columns_to_check = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "cloud_cover",
    "wind_speed_10m",
    "shortwave_radiation",
    "direct_radiation",
    "diffuse_radiation",
    "direct_normal_irradiance",
    "global_tilted_irradiance",
    "sunshine_duration",
    "is_day",
    "P"
]

prepared_data[columns_to_check].describe().T

,count,mean,std,min,25%,50%,75%,max
temperature_2m,437975.0,25.925336,4.092181,6.3,23.6,25.90,28.40,42.30
relative_humidity_2m,437975.0,78.133939,15.489244,14.0,69.0,82.00,91.00,100.00
precipitation,429350.0,0.251486,0.963222,0.0,0.0,0.00,0.10,86.10
cloud_cover,437975.0,75.773873,35.553896,-1.0,51.0,100.00,100.00,104.00
wind_speed_10m,437975.0,10.748927,7.163661,0.0,5.2,8.90,14.80,54.60
shortwave_radiation,437975.0,234.548011,322.923613,0.0,0.0,10.00,459.00,1112.00
direct_radiation,437975.0,161.053432,242.551714,0.0,0.0,4.00,277.00,1015.00
diffuse_radiation,437975.0,73.494578,97.966908,0.0,0.0,6.00,137.00,414.00
direct_normal_irradiance,437975.0,231.537516,296.587933,0.0,0.0,34.20,460.80,1071.10
global_tilted_irradiance,437975.0,235.605186,324.895337,0.0,0.0,9.20,456.40,1149.10
sunshine_duration,437975.0,1565.362660,1732.761103,0.0,0.0,0.00,3600.00,3600.00
is_day,437975.0,0.501248,0.499999,0.0,0.0,1.00,1.00,1.00
P,437975.0,162.701131,223.419464,0.0,0.0,0.28,326.03,819.59

Check Invalid Values

In [35]:
print(
    "Cloud cover below 0:",
    (prepared_data["cloud_cover"] < 0).sum()
)

print(
    "Cloud cover above 100:",
    (prepared_data["cloud_cover"] > 100).sum()
)

print(
    "Humidity below 0:",
    (prepared_data["relative_humidity_2m"] < 0).sum()
)

print(
    "Humidity above 100:",
    (prepared_data["relative_humidity_2m"] > 100).sum()
)

print(
    "Negative precipitation:",
    (prepared_data["precipitation"] < 0).sum()
)

print(
    "Negative sunshine duration:",
    (prepared_data["sunshine_duration"] < 0).sum()
)

print(
    "Sunshine duration above 3600:",
    (prepared_data["sunshine_duration"] > 3600).sum()
)

print(
    "Negative PV output:",
    (prepared_data["P"] < 0).sum()
)

Cloud cover below 0: 22
Cloud cover above 100: 347
Humidity below 0: 0
Humidity above 100: 0
Negative precipitation: 0
Negative sunshine duration: 0
Sunshine duration above 3600: 0
Negative PV output: 0

In [36]:
print(
    "is_day values:",
    sorted(
        prepared_data["is_day"]
        .dropna()
        .unique()
    )
)

is_day values: [np.int64(0), np.int64(1)]

Clean Cloud Cover

In [37]:
prepared_data["cloud_cover"] = (
    prepared_data["cloud_cover"]
    .clip(lower=0, upper=100)
)

In [38]:
print(
    "Cloud cover minimum:",
    prepared_data["cloud_cover"].min()
)

print(
    "Cloud cover maximum:",
    prepared_data["cloud_cover"].max()
)

Cloud cover minimum: 0
Cloud cover maximum: 100

Check Missing Precipitation

In [39]:
missing_precipitation = prepared_data[
    prepared_data["precipitation"].isnull()
]

print(
    "Missing precipitation rows:",
    len(missing_precipitation)
)

print(
    "First missing time:",
    missing_precipitation["time_utc"].min()
)

print(
    "Last missing time:",
    missing_precipitation["time_utc"].max()
)

print(
    "Affected districts:",
    missing_precipitation["district"].nunique()
)

Missing precipitation rows: 8625
First missing time: 2022-11-29 20:00:00+00:00
Last missing time: 2022-12-14 04:00:00+00:00
Affected districts: 25

Check Infinite Values

In [40]:
numeric_data = prepared_data.select_dtypes(
    include=np.number
)

print(
    "Infinite values:",
    np.isinf(numeric_data).sum().sum()
)

Infinite values: 0

Check PVGIS Target

In [41]:
print(
    "Minimum P:",
    prepared_data["P"].min()
)

print(
    "Maximum P:",
    prepared_data["P"].max()
)

print(
    "Missing P:",
    prepared_data["P"].isnull().sum()
)

print(
    "Negative P:",
    (prepared_data["P"] < 0).sum()
)

print(
    "Zero P:",
    (prepared_data["P"] == 0).sum()
)

Minimum P: 0.0
Maximum P: 819.59
Missing P: 0
Negative P: 0
Zero P: 218685

Define Target Variable

In [42]:
target_column = "P"

print("Target variable:", target_column)
print("Target unit: W")
print("Reference PV system: 1 kWp")

Target variable: P
Target unit: W
Reference PV system: 1 kWp

Final Data Check

In [43]:
print("Prepared dataset shape:", prepared_data.shape)
print("Districts:", prepared_data["district"].nunique())

print(
    "Duplicate district/time:",
    prepared_data.duplicated(
        subset=["district", "time_utc"]
    ).sum()
)

print(
    "Missing precipitation:",
    prepared_data["precipitation"].isnull().sum()
)

print(
    "Missing target:",
    prepared_data["P"].isnull().sum()
)

print(
    "Cloud cover range:",
    prepared_data["cloud_cover"].min(),
    "to",
    prepared_data["cloud_cover"].max()
)

Prepared dataset shape: (437975, 26)
Districts: 25
Duplicate district/time: 0
Missing precipitation: 8625
Missing target: 0
Cloud cover range: 0 to 100

In [44]:
prepared_file = os.path.join(
    processed_folder,
    "solar_prepared.csv"
)

prepared_data.to_csv(
    prepared_file,
    index=False
)

print("Saved:", prepared_file)
print("Rows:", len(prepared_data))
print("Columns:", len(prepared_data.columns))

Saved: ../Data/Processed\solar_prepared.csv
Rows: 437975
Columns: 26