In [2]:
import os
import pandas as pd
import requests

Adding Locations

In [3]:
districts = [
    "Colombo",
    "Gampaha",
    "Kalutara",
    "Kandy",
    "Matale",
    "Nuwara Eliya",
    "Galle",
    "Matara",
    "Hambantota",
    "Jaffna",
    "Kilinochchi",
    "Mannar",
    "Mullaitivu",
    "Vavuniya",
    "Batticaloa",
    "Ampara",
    "Trincomalee",
    "Kurunegala",
    "Puttalam",
    "Anuradhapura",
    "Polonnaruwa",
    "Badulla",
    "Monaragala",
    "Ratnapura",
    "Kegalle"
]

location_data = pd.DataFrame(
    districts,
    columns=["district"]
)

location_data

        district
0        Colombo
1        Gampaha
2       Kalutara
3          Kandy
4         Matale
5   Nuwara Eliya
6          Galle
7         Matara
8     Hambantota
9         Jaffna
10   Kilinochchi
11        Mannar
12    Mullaitivu
13      Vavuniya
14    Batticaloa
15        Ampara
16   Trincomalee
17    Kurunegala
18      Puttalam
19  Anuradhapura
20   Polonnaruwa
21       Badulla
22    Monaragala
23     Ratnapura
24       Kegalle

### Get coordinates for the district locations

In [4]:
url = "https://geocoding-api.open-meteo.com/v1/search"

search_names = {
    "Mullaitivu": "Mullaittivu"
}

latitudes = []
longitudes = []
elevations = []

for district in location_data["district"]:
    search_name = search_names.get(district, district)

    params = {
        "name": search_name,
        "count": 10,
        "language": "en",
        "format": "json",
        "countryCode": "LK"
    }

    data = requests.get(url, params=params).json()
    results = data.get("results", [])

    match = None

    for place in results:
        if place.get("name", "").lower() == search_name.lower():
            match = place
            break

    if match:
        latitudes.append(match["latitude"])
        longitudes.append(match["longitude"])
        elevations.append(match.get("elevation"))

        print(
            district,
            match["latitude"],
            match["longitude"],
            match.get("elevation")
        )
    else:
        latitudes.append(None)
        longitudes.append(None)
        elevations.append(None)

        print(district, "Not found")

Colombo 6.93548 79.84868 7.0
Gampaha 7.0897 79.9925 21.0
Kalutara 6.5831 79.9593 7.0
Kandy 7.2906 80.6336 500.0
Matale 7.4698 80.6217 366.0
Nuwara Eliya 6.97078 80.78286 1868.0
Galle 6.0461 80.2103 24.0
Matara 5.94851 80.53528 9.0
Hambantota 6.1241 81.1185 10.0
Jaffna 9.66845 80.00742 7.0
Kilinochchi 9.3961 80.3982 24.0
Mannar 8.98945 79.87842 9.0
Mullaitivu 9.268 80.815 8.0
Vavuniya 8.7514 80.4971 104.0
Batticaloa 7.7102 81.6924 17.0
Ampara 7.29754 81.68202 37.0
Trincomalee 8.5778 81.2289 10.0
Kurunegala 7.4839 80.3683 146.0
Puttalam 8.0362 79.8283 8.0
Anuradhapura 8.31223 80.41306 100.0
Polonnaruwa 7.93965 81.00274 60.0
Badulla 6.9802 81.0577 683.0
Monaragala 6.8714 81.3487 151.0
Ratnapura 6.6858 80.4036 73.0
Kegalle 7.2523 80.3436 176.0

In [5]:
location_data["latitude"] = latitudes
location_data["longitude"] = longitudes
location_data["elevation"] = elevations

location_data

        district  latitude  longitude  elevation
0        Colombo   6.93548   79.84868        7.0
1        Gampaha   7.08970   79.99250       21.0
2       Kalutara   6.58310   79.95930        7.0
3          Kandy   7.29060   80.63360      500.0
4         Matale   7.46980   80.62170      366.0
5   Nuwara Eliya   6.97078   80.78286     1868.0
6          Galle   6.04610   80.21030       24.0
7         Matara   5.94851   80.53528        9.0
8     Hambantota   6.12410   81.11850       10.0
9         Jaffna   9.66845   80.00742        7.0
10   Kilinochchi   9.39610   80.39820       24.0
11        Mannar   8.98945   79.87842        9.0
12    Mullaitivu   9.26800   80.81500        8.0
13      Vavuniya   8.75140   80.49710      104.0
14    Batticaloa   7.71020   81.69240       17.0
15        Ampara   7.29754   81.68202       37.0
16   Trincomalee   8.57780   81.22890       10.0
17    Kurunegala   7.48390   80.36830      146.0
18      Puttalam   8.03620   79.82830        8.0
19  Anuradhapura   8.31223   80.41306      100.0
20   Polonnaruwa   7.93965   81.00274       60.0
21       Badulla   6.98020   81.05770      683.0
22    Monaragala   6.87140   81.34870      151.0
23     Ratnapura   6.68580   80.40360       73.0
24       Kegalle   7.25230   80.34360      176.0

Checking Null and Unique Values

In [6]:
print("Number of districts:", len(location_data))
print("Unique districts:", location_data["district"].nunique())

print("\nMissing values:")
print(location_data.isnull().sum())

print("\nDuplicate coordinates:")
print(location_data.duplicated(["latitude", "longitude"]).sum())

Number of districts: 25
Unique districts: 25

Missing values:
district     0
latitude     0
longitude    0
elevation    0
dtype: int64

Duplicate coordinates:
0

In [7]:
os.makedirs(
    "../Data/Reference",
    exist_ok=True
)

location_data.to_csv(
    "../Data/Reference/location_master.csv",
    index=False
)

In [8]:
pd.read_csv("../Data/Reference/location_master.csv").head()

   district  latitude  longitude  elevation
0   Colombo   6.93548   79.84868        7.0
1   Gampaha   7.08970   79.99250       21.0
2  Kalutara   6.58310   79.95930        7.0
3     Kandy   7.29060   80.63360      500.0
4    Matale   7.46980   80.62170      366.0